# Generated by Django 4.1.7 on 2023-03-13 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_myprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofile',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
