# Generated by Django 4.1.7 on 2023-03-13 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_myprofile_delivery_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='delivery_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
