# Generated by Django 4.1.7 on 2023-03-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_mycart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycart',
            name='book',
        ),
        migrations.AddField(
            model_name='mycart',
            name='book',
            field=models.ManyToManyField(to='book.book'),
        ),
    ]
