# Generated by Django 4.1.7 on 2023-03-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_delete_mycart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='color',
            field=models.CharField(default='#000000', max_length=20, unique=True),
        ),
    ]
