# Generated by Django 4.1.7 on 2023-03-21 17:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_alter_review_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='book_rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
