# Generated by Django 4.1.7 on 2023-03-22 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_review_book_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='likes',
            field=models.FloatField(default=0),
        ),
    ]
