# Generated by Django 4.1.7 on 2023-03-22 03:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_alter_review_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='book_rating',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
