# Generated by Django 4.1.7 on 2023-03-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0015_alter_review_book_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
    ]
