# Generated by Django 4.1.7 on 2023-03-22 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0016_review_is_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='is_liked',
        ),
    ]
