# Generated by Django 4.1.7 on 2023-03-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0020_alter_myprofile_bio_alter_myprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='favorites',
            field=models.ManyToManyField(blank=True, null=True, to='book.book'),
        ),
    ]
